### PR TITLE
CSS & HTML implementation of a YouTube clone.

### PR DESCRIPTION
**Pull request by pointerish**
All features required by the project were met. We have added the following: 

- Navigation bar containing search box and search button as well as icons and logo.
- Video section with a video embedded.
- Video information section containing views, channel name and subscribe button.
- Recommended videos section containing images for video thumbnails, video title, channel name and views count.

### CODE REVIEW

**Review by javitocor — CHANGES_REQUESTED** [review]
# CHANGES REQUIRED ♻️ 

Good job with this your first project, team! 👍 
It really matches the appearance of youtube video player page 👏 
Good use of semantic HTML tags 💯 

However, there are some things to change to make this project approved 🥇 

Check my comments below 👇 

Once the required changes are done, please resubmit the project for a new code review ▶️ 

If you have any question or doubt, you can reach me on Slack

## CHANGES 

You need to add a descriptive README file with a live link to your project, you can use [this](https://raw.githack.com/), in order to approve the project. 💪 

The project has a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

**Comment by pointerish** [comment]
Hi, the README.md has been updated as per your request. I will submit a new code review. Thanks in advance!

**Review by jubaan — CHANGES_REQUESTED** [review]
# :wave::wave::wave: Great work team!

- :100: I've noticed you **improved your README**, it is more descriptive and it's looking good! :sunglasses: 
- :100: Great **Pull Request** and **Commit** messages
- :100: Has all main sections and uses semantic HTML for each.

Still the code need some changes.

## Requested Changes

### [Mandatory]

- [x] We should change ID's for CSS Classes. For future projects Prefer CSS Classes over ID's. Using CSS classes improves code re-usability this helps maintain your code DRY. 

More info: 
- ["The difference between ID and Class"](https://css-tricks.com/the-difference-between-id-and-class/)
- [CSS Best Practices](https://speckyboy.com/good-bad-css-practices/)

### [OPTIONAL]

As OPTIONAL implies, next points are suggestions for this and future projects. **Your main focus should be on the MANDATORY requirements.**

- [ ] 2 space indentation as it increases readability. This improves maintainability, aides collaborative efforts and makes for a better developer experience overall.

- [x] CSS selectors should have 1 line space between them.

:-1:  Actual
```
.recommended-title {
    display: inline;
    font-weight: bold;
    font-size: .8rem;
}
.recommended-channel, .recommended-views {
    font-size: .7rem;
    margin: 0;
    padding: 0;
}
.recommended-info {
    margin: 0 5px;
}
```
:+1: Improved with 1 line break between ending and next selector
```
.recommended-title {
    display: inline;
    font-weight: bold;
    font-size: .8rem;
}

.recommended-channel, .recommended-views {
    font-size: .7rem;
    margin: 0;
    padding: 0;
}

.recommended-info {
    margin: 0 5px;
}
```

- [ ] CSS styles that uses multiple selectors should be in new-line each.

:-1:  Actual. The reader could confuse it as a parent with a child selector.
```
.recommended-channel, .recommended-views {
    font-size: .7rem;
    margin: 0;
    padding: 0;
}
```
:+1: Improved. Its easier to read and identified all related selectors.
```
.recommended-channel, 
.recommended-views {
    font-size: .7rem;
    margin: 0;
    padding: 0;
}
```
- [x]  Clean CSS by refactoring, creating utility CSS from repeated properties. Example:

Actual:
```
#navigation-bar div {
    **display: flex;**
    align-items: center;
}
main {
    **display: flex;**
    background-color: rgb(235, 235,224)
}
#video-info {
    **display: flex;**
    **font-size: 14px;**
    padding: 5px;
}
#channel-info {
    **display: flex;**
    **font-size: 14px;**
   ...
}
```
Improved:
```
.d-flex {
    display: flex
}

.font-14 {
    font: 14px;
} 

#navigation-bar div {
    align-items: center;
}

main {
    background-color: rgb(235, 235,224)
}

#video-info {
    padding: 5px;
}

#channel-info {
   ...
}
```

**Comment by pointerish** [comment]
Hi @jubaan, thanks  for the feedback. We've made the changes and we are submitting a new review request.

**Review by teekaytech — APPROVED** [review]
# Status : Approved :heavy_check_mark: 

### Hello team, 

-**You've done an amazing job: :clap:**
:point_right: I personally appreciate your efforts in paying attention to details :100: 
**Your project passed all the mandatory requirements.  :muscle: This project is now approved :ok:. You can continue to the next project.**

**[OPTIONAL]** 
_The features listed below are optional. You may not implement it but if you do, it makes your project more professional._

- [ ] You are encouraged to build the comments section of this page.

- [ ] You are also encouraged to implement the footer section

* * *

**Congratulations! :tada: 
It's a pleasure to review your project :blush: 
Good luck with your next project :100: 
Happy Coding :man_technologist:**

_With all my regards,_
Taofeek Olalere
@taofeekolalere {slack}
@teekaytech {github}

**Pull request merged**
